name: urban-tree-detection
dependencies:
  - python=3.8
  - tensorflow-gpu=2.4.1
  - numpy=1.19.2
  - imageio
  - rasterio
  - geopandas
  - h5py
  - scipy
  - tqdm
  - pip
  - pip:
    - optuna
    - scikit-image
    - scikit-learn
